// Generated by gencpp from file custom_msgs/GetObject.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_GETOBJECT_H
#define CUSTOM_MSGS_MESSAGE_GETOBJECT_H

#include <ros/service_traits.h>


#include <custom_msgs/GetObjectRequest.h>
#include <custom_msgs/GetObjectResponse.h>


namespace custom_msgs
{

struct GetObject
{

typedef GetObjectRequest Request;
typedef GetObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetObject
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::GetObject > {
  static const char* value()
  {
    return "e494291815697d37bb402083d19502dd";
  }

  static const char* value(const ::custom_msgs::GetObject&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::GetObject > {
  static const char* value()
  {
    return "custom_msgs/GetObject";
  }

  static const char* value(const ::custom_msgs::GetObject&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::GetObjectRequest> should match
// service_traits::MD5Sum< ::custom_msgs::GetObject >
template<>
struct MD5Sum< ::custom_msgs::GetObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::GetObject >::value();
  }
  static const char* value(const ::custom_msgs::GetObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::GetObjectRequest> should match
// service_traits::DataType< ::custom_msgs::GetObject >
template<>
struct DataType< ::custom_msgs::GetObjectRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::GetObject >::value();
  }
  static const char* value(const ::custom_msgs::GetObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::GetObjectResponse> should match
// service_traits::MD5Sum< ::custom_msgs::GetObject >
template<>
struct MD5Sum< ::custom_msgs::GetObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::GetObject >::value();
  }
  static const char* value(const ::custom_msgs::GetObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::GetObjectResponse> should match
// service_traits::DataType< ::custom_msgs::GetObject >
template<>
struct DataType< ::custom_msgs::GetObjectResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::GetObject >::value();
  }
  static const char* value(const ::custom_msgs::GetObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_GETOBJECT_H
