// Generated by gencpp from file handeye_cam/Msg.msg
// DO NOT EDIT!


#ifndef HANDEYE_CAM_MESSAGE_MSG_H
#define HANDEYE_CAM_MESSAGE_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace handeye_cam
{
template <class ContainerAllocator>
struct Msg_
{
  typedef Msg_<ContainerAllocator> Type;

  Msg_()
    : w(0)
    , h(0)
    , num(0)  {
    }
  Msg_(const ContainerAllocator& _alloc)
    : w(0)
    , h(0)
    , num(0)  {
  (void)_alloc;
    }



   typedef int32_t _w_type;
  _w_type w;

   typedef int32_t _h_type;
  _h_type h;

   typedef int32_t _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::handeye_cam::Msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::handeye_cam::Msg_<ContainerAllocator> const> ConstPtr;

}; // struct Msg_

typedef ::handeye_cam::Msg_<std::allocator<void> > Msg;

typedef boost::shared_ptr< ::handeye_cam::Msg > MsgPtr;
typedef boost::shared_ptr< ::handeye_cam::Msg const> MsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::handeye_cam::Msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::handeye_cam::Msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::handeye_cam::Msg_<ContainerAllocator1> & lhs, const ::handeye_cam::Msg_<ContainerAllocator2> & rhs)
{
  return lhs.w == rhs.w &&
    lhs.h == rhs.h &&
    lhs.num == rhs.num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::handeye_cam::Msg_<ContainerAllocator1> & lhs, const ::handeye_cam::Msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace handeye_cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::handeye_cam::Msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::handeye_cam::Msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::handeye_cam::Msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::handeye_cam::Msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::handeye_cam::Msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::handeye_cam::Msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::handeye_cam::Msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7443ea74a07cdd552dd4948fd2619cf";
  }

  static const char* value(const ::handeye_cam::Msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7443ea74a07cdd5ULL;
  static const uint64_t static_value2 = 0x52dd4948fd2619cfULL;
};

template<class ContainerAllocator>
struct DataType< ::handeye_cam::Msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "handeye_cam/Msg";
  }

  static const char* value(const ::handeye_cam::Msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::handeye_cam::Msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 w\n"
"int32 h\n"
"int32 num\n"
;
  }

  static const char* value(const ::handeye_cam::Msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::handeye_cam::Msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.w);
      stream.next(m.h);
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::handeye_cam::Msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::handeye_cam::Msg_<ContainerAllocator>& v)
  {
    s << indent << "w: ";
    Printer<int32_t>::stream(s, indent + "  ", v.w);
    s << indent << "h: ";
    Printer<int32_t>::stream(s, indent + "  ", v.h);
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HANDEYE_CAM_MESSAGE_MSG_H
