// Generated by gencpp from file tomato_detection/switch_camResponse.msg
// DO NOT EDIT!


#ifndef TOMATO_DETECTION_MESSAGE_SWITCH_CAMRESPONSE_H
#define TOMATO_DETECTION_MESSAGE_SWITCH_CAMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tomato_detection
{
template <class ContainerAllocator>
struct switch_camResponse_
{
  typedef switch_camResponse_<ContainerAllocator> Type;

  switch_camResponse_()
    : data(0)  {
    }
  switch_camResponse_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::tomato_detection::switch_camResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tomato_detection::switch_camResponse_<ContainerAllocator> const> ConstPtr;

}; // struct switch_camResponse_

typedef ::tomato_detection::switch_camResponse_<std::allocator<void> > switch_camResponse;

typedef boost::shared_ptr< ::tomato_detection::switch_camResponse > switch_camResponsePtr;
typedef boost::shared_ptr< ::tomato_detection::switch_camResponse const> switch_camResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tomato_detection::switch_camResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tomato_detection::switch_camResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tomato_detection::switch_camResponse_<ContainerAllocator1> & lhs, const ::tomato_detection::switch_camResponse_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tomato_detection::switch_camResponse_<ContainerAllocator1> & lhs, const ::tomato_detection::switch_camResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tomato_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tomato_detection::switch_camResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tomato_detection::switch_camResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tomato_detection::switch_camResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tomato_detection::switch_camResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tomato_detection::switch_camResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tomato_detection::switch_camResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tomato_detection::switch_camResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c8164229e7d2c17eb95e9231617fdee";
  }

  static const char* value(const ::tomato_detection::switch_camResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c8164229e7d2c17ULL;
  static const uint64_t static_value2 = 0xeb95e9231617fdeeULL;
};

template<class ContainerAllocator>
struct DataType< ::tomato_detection::switch_camResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tomato_detection/switch_camResponse";
  }

  static const char* value(const ::tomato_detection::switch_camResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tomato_detection::switch_camResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 data\n"
;
  }

  static const char* value(const ::tomato_detection::switch_camResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tomato_detection::switch_camResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct switch_camResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tomato_detection::switch_camResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tomato_detection::switch_camResponse_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOMATO_DETECTION_MESSAGE_SWITCH_CAMRESPONSE_H
