// Generated by gencpp from file tomato_detection/switch_cam.msg
// DO NOT EDIT!


#ifndef TOMATO_DETECTION_MESSAGE_SWITCH_CAM_H
#define TOMATO_DETECTION_MESSAGE_SWITCH_CAM_H

#include <ros/service_traits.h>


#include <tomato_detection/switch_camRequest.h>
#include <tomato_detection/switch_camResponse.h>


namespace tomato_detection
{

struct switch_cam
{

typedef switch_camRequest Request;
typedef switch_camResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct switch_cam
} // namespace tomato_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tomato_detection::switch_cam > {
  static const char* value()
  {
    return "c1d0f6b5d3ccfee714fe1fdff0074c75";
  }

  static const char* value(const ::tomato_detection::switch_cam&) { return value(); }
};

template<>
struct DataType< ::tomato_detection::switch_cam > {
  static const char* value()
  {
    return "tomato_detection/switch_cam";
  }

  static const char* value(const ::tomato_detection::switch_cam&) { return value(); }
};


// service_traits::MD5Sum< ::tomato_detection::switch_camRequest> should match
// service_traits::MD5Sum< ::tomato_detection::switch_cam >
template<>
struct MD5Sum< ::tomato_detection::switch_camRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tomato_detection::switch_cam >::value();
  }
  static const char* value(const ::tomato_detection::switch_camRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tomato_detection::switch_camRequest> should match
// service_traits::DataType< ::tomato_detection::switch_cam >
template<>
struct DataType< ::tomato_detection::switch_camRequest>
{
  static const char* value()
  {
    return DataType< ::tomato_detection::switch_cam >::value();
  }
  static const char* value(const ::tomato_detection::switch_camRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tomato_detection::switch_camResponse> should match
// service_traits::MD5Sum< ::tomato_detection::switch_cam >
template<>
struct MD5Sum< ::tomato_detection::switch_camResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tomato_detection::switch_cam >::value();
  }
  static const char* value(const ::tomato_detection::switch_camResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tomato_detection::switch_camResponse> should match
// service_traits::DataType< ::tomato_detection::switch_cam >
template<>
struct DataType< ::tomato_detection::switch_camResponse>
{
  static const char* value()
  {
    return DataType< ::tomato_detection::switch_cam >::value();
  }
  static const char* value(const ::tomato_detection::switch_camResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOMATO_DETECTION_MESSAGE_SWITCH_CAM_H
