// Generated by gencpp from file tomato_detection/SelectTomato.msg
// DO NOT EDIT!


#ifndef TOMATO_DETECTION_MESSAGE_SELECTTOMATO_H
#define TOMATO_DETECTION_MESSAGE_SELECTTOMATO_H

#include <ros/service_traits.h>


#include <tomato_detection/SelectTomatoRequest.h>
#include <tomato_detection/SelectTomatoResponse.h>


namespace tomato_detection
{

struct SelectTomato
{

typedef SelectTomatoRequest Request;
typedef SelectTomatoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SelectTomato
} // namespace tomato_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tomato_detection::SelectTomato > {
  static const char* value()
  {
    return "740697c9bd3592ba5c586821d8c52d19";
  }

  static const char* value(const ::tomato_detection::SelectTomato&) { return value(); }
};

template<>
struct DataType< ::tomato_detection::SelectTomato > {
  static const char* value()
  {
    return "tomato_detection/SelectTomato";
  }

  static const char* value(const ::tomato_detection::SelectTomato&) { return value(); }
};


// service_traits::MD5Sum< ::tomato_detection::SelectTomatoRequest> should match
// service_traits::MD5Sum< ::tomato_detection::SelectTomato >
template<>
struct MD5Sum< ::tomato_detection::SelectTomatoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tomato_detection::SelectTomato >::value();
  }
  static const char* value(const ::tomato_detection::SelectTomatoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tomato_detection::SelectTomatoRequest> should match
// service_traits::DataType< ::tomato_detection::SelectTomato >
template<>
struct DataType< ::tomato_detection::SelectTomatoRequest>
{
  static const char* value()
  {
    return DataType< ::tomato_detection::SelectTomato >::value();
  }
  static const char* value(const ::tomato_detection::SelectTomatoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tomato_detection::SelectTomatoResponse> should match
// service_traits::MD5Sum< ::tomato_detection::SelectTomato >
template<>
struct MD5Sum< ::tomato_detection::SelectTomatoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tomato_detection::SelectTomato >::value();
  }
  static const char* value(const ::tomato_detection::SelectTomatoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tomato_detection::SelectTomatoResponse> should match
// service_traits::DataType< ::tomato_detection::SelectTomato >
template<>
struct DataType< ::tomato_detection::SelectTomatoResponse>
{
  static const char* value()
  {
    return DataType< ::tomato_detection::SelectTomato >::value();
  }
  static const char* value(const ::tomato_detection::SelectTomatoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOMATO_DETECTION_MESSAGE_SELECTTOMATO_H
