// Generated by gencpp from file tomato_detection/SelectTomatoResponse.msg
// DO NOT EDIT!


#ifndef TOMATO_DETECTION_MESSAGE_SELECTTOMATORESPONSE_H
#define TOMATO_DETECTION_MESSAGE_SELECTTOMATORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tomato_detection
{
template <class ContainerAllocator>
struct SelectTomatoResponse_
{
  typedef SelectTomatoResponse_<ContainerAllocator> Type;

  SelectTomatoResponse_()
    : tomatoPos()  {
    }
  SelectTomatoResponse_(const ContainerAllocator& _alloc)
    : tomatoPos(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _tomatoPos_type;
  _tomatoPos_type tomatoPos;





  typedef boost::shared_ptr< ::tomato_detection::SelectTomatoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tomato_detection::SelectTomatoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SelectTomatoResponse_

typedef ::tomato_detection::SelectTomatoResponse_<std::allocator<void> > SelectTomatoResponse;

typedef boost::shared_ptr< ::tomato_detection::SelectTomatoResponse > SelectTomatoResponsePtr;
typedef boost::shared_ptr< ::tomato_detection::SelectTomatoResponse const> SelectTomatoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tomato_detection::SelectTomatoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tomato_detection::SelectTomatoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tomato_detection::SelectTomatoResponse_<ContainerAllocator1> & lhs, const ::tomato_detection::SelectTomatoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.tomatoPos == rhs.tomatoPos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tomato_detection::SelectTomatoResponse_<ContainerAllocator1> & lhs, const ::tomato_detection::SelectTomatoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tomato_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tomato_detection::SelectTomatoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tomato_detection::SelectTomatoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tomato_detection::SelectTomatoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tomato_detection::SelectTomatoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tomato_detection::SelectTomatoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tomato_detection::SelectTomatoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tomato_detection::SelectTomatoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ec060072f29f1fa2698deb242ab0c3e";
  }

  static const char* value(const ::tomato_detection::SelectTomatoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ec060072f29f1faULL;
  static const uint64_t static_value2 = 0x2698deb242ab0c3eULL;
};

template<class ContainerAllocator>
struct DataType< ::tomato_detection::SelectTomatoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tomato_detection/SelectTomatoResponse";
  }

  static const char* value(const ::tomato_detection::SelectTomatoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tomato_detection::SelectTomatoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] tomatoPos\n"
"\n"
;
  }

  static const char* value(const ::tomato_detection::SelectTomatoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tomato_detection::SelectTomatoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tomatoPos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SelectTomatoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tomato_detection::SelectTomatoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tomato_detection::SelectTomatoResponse_<ContainerAllocator>& v)
  {
    s << indent << "tomatoPos[]" << std::endl;
    for (size_t i = 0; i < v.tomatoPos.size(); ++i)
    {
      s << indent << "  tomatoPos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.tomatoPos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOMATO_DETECTION_MESSAGE_SELECTTOMATORESPONSE_H
