// Generated by gencpp from file custom_msgs/AddTwoInts.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_ADDTWOINTS_H
#define CUSTOM_MSGS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <custom_msgs/AddTwoIntsRequest.h>
#include <custom_msgs/AddTwoIntsResponse.h>


namespace custom_msgs
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::AddTwoInts > {
  static const char* value()
  {
    return "713e5cf1444846805670f946f08bfc96";
  }

  static const char* value(const ::custom_msgs::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::AddTwoInts > {
  static const char* value()
  {
    return "custom_msgs/AddTwoInts";
  }

  static const char* value(const ::custom_msgs::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::custom_msgs::AddTwoInts >
template<>
struct MD5Sum< ::custom_msgs::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::AddTwoInts >::value();
  }
  static const char* value(const ::custom_msgs::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::AddTwoIntsRequest> should match
// service_traits::DataType< ::custom_msgs::AddTwoInts >
template<>
struct DataType< ::custom_msgs::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::AddTwoInts >::value();
  }
  static const char* value(const ::custom_msgs::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::custom_msgs::AddTwoInts >
template<>
struct MD5Sum< ::custom_msgs::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::AddTwoInts >::value();
  }
  static const char* value(const ::custom_msgs::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::AddTwoIntsResponse> should match
// service_traits::DataType< ::custom_msgs::AddTwoInts >
template<>
struct DataType< ::custom_msgs::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::AddTwoInts >::value();
  }
  static const char* value(const ::custom_msgs::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_ADDTWOINTS_H
