// Generated by gencpp from file custom_msgs/GetObjectRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_GETOBJECTREQUEST_H
#define CUSTOM_MSGS_MESSAGE_GETOBJECTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct GetObjectRequest_
{
  typedef GetObjectRequest_<ContainerAllocator> Type;

  GetObjectRequest_()
    : item()
    , id(0)  {
    }
  GetObjectRequest_(const ContainerAllocator& _alloc)
    : item(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _item_type;
  _item_type item;

   typedef int64_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::custom_msgs::GetObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::GetObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetObjectRequest_

typedef ::custom_msgs::GetObjectRequest_<std::allocator<void> > GetObjectRequest;

typedef boost::shared_ptr< ::custom_msgs::GetObjectRequest > GetObjectRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::GetObjectRequest const> GetObjectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::GetObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::GetObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::GetObjectRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::GetObjectRequest_<ContainerAllocator2> & rhs)
{
  return lhs.item == rhs.item &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::GetObjectRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::GetObjectRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::GetObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::GetObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::GetObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::GetObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::GetObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::GetObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::GetObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "582eeac6e6e1af2d7d31aa5c5948e265";
  }

  static const char* value(const ::custom_msgs::GetObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x582eeac6e6e1af2dULL;
  static const uint64_t static_value2 = 0x7d31aa5c5948e265ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::GetObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/GetObjectRequest";
  }

  static const char* value(const ::custom_msgs::GetObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::GetObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string item\n"
"int64 id\n"
;
  }

  static const char* value(const ::custom_msgs::GetObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::GetObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.item);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::GetObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::GetObjectRequest_<ContainerAllocator>& v)
  {
    s << indent << "item: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.item);
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_GETOBJECTREQUEST_H
