# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
mouth:
  ID: 4
  Return_Delay_Time: 0
  #torque_enable: 24    # Address for torque enable
  #Present_Position: 6    # Address for the current position
  #Goal_Position: 30    # Address for goal position
  #Len_MX_GOAL_POSITION: 2     # MX's have different message lengths in Protocol 1 vs. 2
                                        # and protocol 1.0 does not use present_position length
hand:
  ID: 2
  Return_Delay_Time: 0



